# Generated by Django 4.2.11 on 2024-06-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(max_length=128, null=True, unique=True),
        ),
    ]
