# Generated by Django 4.2.11 on 2024-06-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_populate_productcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=256, null=True, unique=True),
        ),
    ]
