# Generated by Django 4.2.11 on 2024-06-27 06:33

from django.db import migrations

from time import time

def populate_isbn_with_time(apps, schema_editor):
    model = apps.get_model('products', 'Product')

    for row in model.objects.all():
        row.isbn = str(time())[:-2]
        row.save(update_fields=['isbn'])

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_author_isbn_page_count_publication_year_publisher'),
    ]

    operations = [
        migrations.RunPython(populate_isbn_with_time,
                             reverse_code=migrations.RunPython.noop)
    ]

