# Generated by Django 4.2.11 on 2024-06-27 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_populate_product_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ManyToManyField(to='products.author'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='page_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='publication_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.publisher'),
        ),
    ]
