# Generated by Django 4.2.11 on 2024-06-29 05:56

import common.utils.models.models_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_author_isbn_page_count_publication_year_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, storage=common.utils.models.models_storages.OverwriteImageStorage, upload_to='products_images'),
        ),
    ]
